version: '3.6'

services:
  db_feirouu:
    image: postgres
    container_name: db_feirouu
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_feirouu
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
  app:
    build: .
    container_name: feirouu_backend
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_feirouu:5432/db_feirouu
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db_feirouu
    links:
      - db_feirouu
    expose:
      - 8082
    ports:
      - 8082:8082