version: '3.6'

services:
  db:
    image: postgres
    container_name: db_feirouu
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_feirouu
    ports:
      - 5432:5432
    expose:
      - 5432