spring:
  datasource:
    initialization-mode: never
    platform: postgres
    url: ${URL_DATABASE}
    username: ${USER_DATABASE}
    password: ${PASSWORD_DATABASE}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
