spring:
  datasource:
    initialization-mode: never
    platform: postgres
    url: jdbc:postgresql://ec2-34-231-221-151.compute-1.amazonaws.com:5432/df0m8no30bsiov
    username: sreoghkiuyuhrz
    password: 1ec4dac8ce17a68c375ef0c7d69ada2745ac472a7a357f075ddcf21d9ffcc222
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
