server:
  port: 9999

spring:
  datasource:
    initialization-mode: never
    platform: postgres
    url: jdbc:postgresql://localhost:5432/db_feirouu
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


jwt:
  expiration: 1000000000
  secret: 123